cab exception check
btc-ag/clang-tools-extra pull request #11
Opened 2018-10-04 13:47 UTC by GerrietReents

This check looks for wrong usage of cab exceptions. It has a bool parameter btc-use-of-cab-exception.CABExceptionAsPointer to define wanted convention.

2018-10-04 16:18 UTC, sigiesec requested changes

2018-10-04 16:18 UTC, sigiesec commented on clang-tidy/btc/CABExceptionCheck.cpp
> +          .bind("CABException"),
extract "CABException" into a constant, it is used multiple times

2018-10-04 16:18 UTC, sigiesec commented on clang-tidy/btc/CABExceptionCheck.cpp
> +                       " is catched as a pointer. It must be catched as const "
catched -> caught (several places)

2018-10-04 16:18 UTC, sigiesec commented on clang-tidy/btc/CABExceptionCheck.cpp
> +  Finder->addMatcher(cxxThrowExpr().bind("CxxThrowExpr"), this);
extract "CxxThrowExpr" into a constant, it is used multiple times

2018-10-05 07:25 UTC, GerrietReents commented on clang-tidy/btc/CABExceptionCheck.cpp
> +          .bind("CABException"),
Yes, fixed now!

2018-10-05 07:25 UTC, GerrietReents commented on clang-tidy/btc/CABExceptionCheck.cpp
> +                       " is catched as a pointer. It must be catched as const "
Yes, fixed now!

2018-10-05 07:26 UTC, GerrietReents commented on clang-tidy/btc/CABExceptionCheck.cpp
> +  Finder->addMatcher(cxxThrowExpr().bind("CxxThrowExpr"), this);
Yes, fixed now!

2018-10-05 07:37 UTC, sigiesec approved these changes

2018-10-05 08:10 UTC, merged